/*Classe: TelaIdentificaLingua
  Pacote: protototipominop.view
  Funcionalidade: Essa classe representa a tela na qual realiza-se a identificação
  dos idiomas das mensagens da coleção através da API do Google.
  Autor: Leandro Matioli Santos
*/

package protototipominop.view;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author Leandro
 */
public class TelaIdentificaLingua extends javax.swing.JPanel {

    String caminhoArquivo;
    public static SwingWorker worker;

    /** Creates new form TelaIdentificaLingua */
    public TelaIdentificaLingua() {
        initComponents();

        btnCancelar.setEnabled(false);

        barraProgIdLingua.setVisible(false);

        JFileChooser fileChooser = new JFileChooser();

        fileChooser.showOpenDialog(this);

        caminhoArquivo = fileChooser.getSelectedFile().getAbsolutePath();

        barraArquivoAtehMomento.setVisible(false);
        labelCriarArquivoSeparado.setVisible(false);
        btnNao.setVisible(false);
        btnSim.setVisible(false);


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoConverterJson = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnIniciarIdentificacao = new javax.swing.JButton();
        barraProgIdLingua = new javax.swing.JProgressBar();
        btnCancelar = new javax.swing.JButton();
        labelCriarArquivoSeparado = new javax.swing.JLabel();
        btnSim = new javax.swing.JButton();
        btnNao = new javax.swing.JButton();
        barraArquivoAtehMomento = new javax.swing.JProgressBar();

        setPreferredSize(new java.awt.Dimension(733, 428));

        textoConverterJson.setFont(new java.awt.Font("Tahoma", 0, 18));
        textoConverterJson.setText("Identificar os idiomas contidos no arquivo especificado:");

        btnIniciarIdentificacao.setText("Iniciar Identificação");
        btnIniciarIdentificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarIdentificacaoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Parar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        labelCriarArquivoSeparado.setText("Deseja criar um arquivo separado com a identificação até o momento?");

        btnSim.setText("Sim");
        btnSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimActionPerformed(evt);
            }
        });

        btnNao.setText("Não");
        btnNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(barraProgIdLingua, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(labelCriarArquivoSeparado)
                .addGap(18, 18, 18)
                .addComponent(btnSim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNao)
                .addGap(91, 91, 91))
            .addGroup(layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(barraArquivoAtehMomento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(textoConverterJson)
                .addGap(142, 142, 142))
            .addGroup(layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIniciarIdentificacao, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(308, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoConverterJson)
                .addGap(94, 94, 94)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(barraProgIdLingua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIniciarIdentificacao)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCriarArquivoSeparado)
                    .addComponent(btnSim)
                    .addComponent(btnNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraArquivoAtehMomento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarIdentificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarIdentificacaoActionPerformed

        btnIniciarIdentificacao.setEnabled(false);

        btnCancelar.setEnabled(true);

        //Cria um SwingWorker para não travar a tela e preencher a barra de progresso
        worker = new SwingWorker <Object, Object>() {

            @Override
            protected Object doInBackground() throws Exception {

                barraProgIdLingua.setVisible(true);
                barraProgIdLingua.setStringPainted(true);
                barraProgIdLingua.setMaximum(TelaPrincipal.baseDeTextoController.contaLinhas(caminhoArquivo));

                TelaPrincipal.baseDeTextoController.identificaLingua(caminhoArquivo);

                JOptionPane.showMessageDialog(null, "Identificação realizada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

                btnCancelar.setEnabled(false);

                return null;
            }
            
        };

        worker.execute();
        
    }//GEN-LAST:event_btnIniciarIdentificacaoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        //Cancela a thread
        worker.cancel(true);

        btnCancelar.setEnabled(false);

        labelCriarArquivoSeparado.setVisible(true);
        btnNao.setVisible(true);
        btnSim.setVisible(true);

}//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNaoActionPerformed

        labelCriarArquivoSeparado.setEnabled(false);
        btnNao.setEnabled(false);
        btnSim.setEnabled(false);

    }//GEN-LAST:event_btnNaoActionPerformed

    private void btnSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimActionPerformed

        labelCriarArquivoSeparado.setEnabled(false);
        btnNao.setEnabled(false);
        btnSim.setEnabled(false);

        barraArquivoAtehMomento.setVisible(true);

        //Recupera a quantidade de docs que foram processados ja
        int docParou = Integer.valueOf(barraProgIdLingua.getString().split(" ")[0]);

        //Coloca o maximo como a quantidade restante de documentos
        barraArquivoAtehMomento.setMaximum(barraProgIdLingua.getMaximum() - docParou);
        barraArquivoAtehMomento.setStringPainted(true);

        //Cria um SwingWorker para não travar a tela e preencher a barra de progresso
        new SwingWorker() {

            @Override
            protected Object doInBackground() throws Exception {

                TelaPrincipal.baseDeTextoController.separaArquivoIdLinguas(caminhoArquivo);

                return null;
            }

        }.execute();

    }//GEN-LAST:event_btnSimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JProgressBar barraArquivoAtehMomento;
    public static javax.swing.JProgressBar barraProgIdLingua;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIniciarIdentificacao;
    private javax.swing.JButton btnNao;
    private javax.swing.JButton btnSim;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelCriarArquivoSeparado;
    private javax.swing.JLabel textoConverterJson;
    // End of variables declaration//GEN-END:variables

}
