/*Classe: TelaConverteJson
  Pacote: protototipominop.view
  Funcionalidade: Essa classe representa a tela responsável pela conversão de mensagens
  no formato JSON para apenas texto.
  Autor: Leandro Matioli Santos
*/

package protototipominop.view;

import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author Leandro
 */
public class TelaConverteJson extends javax.swing.JPanel {

    /** Creates new form TelaConverteJson */
    public TelaConverteJson() {
        initComponents();
        
        barraProgConverteJson.setVisible(true);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoConverterJson = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        barraProgConverteJson = new javax.swing.JProgressBar();
        btnConverter = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(733, 428));

        textoConverterJson.setFont(new java.awt.Font("Tahoma", 0, 18));
        textoConverterJson.setText("Converter base Json para texto comum...");

        btnConverter.setText("Converter");
        btnConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConverterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(barraProgConverteJson, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textoConverterJson)
                        .addGap(198, 198, 198))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnConverter)
                        .addGap(322, 322, 322))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoConverterJson)
                .addGap(114, 114, 114)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(barraProgConverteJson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConverter)
                .addContainerGap(131, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConverterActionPerformed

        barraProgConverteJson.setMaximum(TelaPrincipal.baseDeTextoController.baseDeTextoModel.getQtdTextos());
        barraProgConverteJson.setStringPainted(true);

        btnConverter.setEnabled(false);

        //Cria um SwingWorker para não travar a tela e preencher a barra de progresso
        new SwingWorker() {

            @Override
            protected Object doInBackground() throws Exception {

                TelaPrincipal.baseDeTextoController.escreveArquivoTextoConvertidoDoJson(TelaPrincipal.baseDeTextoController.baseDeTextoModel.getCaminhoAbsoluto());

                JOptionPane.showMessageDialog(null, "Conversão realizada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

                return null;

            }
            
        }.execute();

        


    }//GEN-LAST:event_btnConverterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JProgressBar barraProgConverteJson;
    private javax.swing.JButton btnConverter;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel textoConverterJson;
    // End of variables declaration//GEN-END:variables

}
