/*Classe: TelaAmostra
  Pacote: protototipominop.view
  Funcionalidade: Essa classe representa a tela responsável por exibir a saída do
  svmlight para o treinamento realizado.
  Autor: Leandro Matioli Santos
*/

package protototipominop.view;

/**
 *
 * @author Leandro
 */
public class TelaSaidaTreinamento extends javax.swing.JPanel {

    /** Creates new form TelaSaidaTreinamento */
    public TelaSaidaTreinamento() {

        initComponents();

        textAreaSaidaTreino.setEditable(false);

        String arquivoClassificacao = TelaPrincipal.baseDeTextoController.baseDeTextoModel.getCaminhoAbsoluto()+"-TREINAMENTO-PREPROCESSADO";
        String arquivoModelo = TelaPrincipal.baseDeTextoController.retornaNomeArquivo(TelaPrincipal.baseDeTextoController.baseDeTextoModel.getCaminhoAbsoluto()) + "-MODELOSVM";

        TelaPrincipal.baseDeTextoController.realizaTreinamentoSVM(arquivoClassificacao, arquivoModelo);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoSaidaSVMTreinamento = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaSaidaTreino = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(733, 428));

        textoSaidaSVMTreinamento.setFont(new java.awt.Font("Tahoma", 0, 18));
        textoSaidaSVMTreinamento.setText("Saída do SVM (Treinamento):");

        textAreaSaidaTreino.setColumns(20);
        textAreaSaidaTreino.setRows(5);
        jScrollPane1.setViewportView(textAreaSaidaTreino);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(254, Short.MAX_VALUE)
                .addComponent(textoSaidaSVMTreinamento)
                .addGap(245, 245, 245))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoSaidaSVMTreinamento)
                .addContainerGap(395, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(112, 112, 112)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addGap(18, 18, 18)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(112, 112, 112)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public static javax.swing.JTextArea textAreaSaidaTreino;
    private javax.swing.JLabel textoSaidaSVMTreinamento;
    // End of variables declaration//GEN-END:variables

}
