/*Classe: TelaDescreveClassificacao
  Pacote: protototipominop.view
  Funcionalidade: Essa classe representa a tela na qual defini-se de que tipo será
  a classificação realizada.
  Autor: Leandro Matioli Santos
*/

package protototipominop.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Leandro
 */
public class TelaDescreveClassificacao extends javax.swing.JPanel {

    public static String classificacaoEscolhida;
    public static String assunto;

    /** Creates new form TelaDescreveClassificacao */
    public TelaDescreveClassificacao() {
        initComponents();

        //Adiciona os buttons ao grupo
        btnGrupo.add(radBtnPosNeg);
        btnGrupo.add(radBtnNeutroOp);
        btnGrupo.add(radBtnOutraClassificacao);

        tfOutraClassificacaoEsq.setEnabled(false);
        tfOutraClassificacaoDir.setEnabled(false);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupo = new javax.swing.ButtonGroup();
        textoConverterJson = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        radBtnNeutroOp = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        radBtnPosNeg = new javax.swing.JRadioButton();
        radBtnOutraClassificacao = new javax.swing.JRadioButton();
        tfOutraClassificacaoEsq = new javax.swing.JTextField();
        btnConfirmaSelecao = new javax.swing.JButton();
        labelAssunto = new javax.swing.JLabel();
        tfAssunto = new javax.swing.JTextField();
        labelBarra = new javax.swing.JLabel();
        tfOutraClassificacaoDir = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(733, 428));

        textoConverterJson.setFont(new java.awt.Font("Tahoma", 0, 18));
        textoConverterJson.setText("Defina que tipo de classificação foi realizada:");

        radBtnNeutroOp.setText("Opinativo/Neutro");
        radBtnNeutroOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnNeutroOpActionPerformed(evt);
            }
        });

        radBtnPosNeg.setText("Positivo/Negativo");
        radBtnPosNeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnPosNegActionPerformed(evt);
            }
        });

        radBtnOutraClassificacao.setText("Outra");
        radBtnOutraClassificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnOutraClassificacaoActionPerformed(evt);
            }
        });

        btnConfirmaSelecao.setText("Confirma Seleção");
        btnConfirmaSelecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmaSelecaoActionPerformed(evt);
            }
        });

        labelAssunto.setText("Assunto:");

        labelBarra.setText("/");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textoConverterJson)
                        .addGap(180, 180, 180))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radBtnPosNeg)
                    .addComponent(radBtnNeutroOp)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radBtnOutraClassificacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfOutraClassificacaoEsq, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelBarra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfOutraClassificacaoDir, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(labelAssunto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfAssunto, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addGap(202, 202, 202))
            .addGroup(layout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(btnConfirmaSelecao)
                .addContainerGap(313, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoConverterJson)
                .addGap(49, 49, 49)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(radBtnNeutroOp)
                .addGap(18, 18, 18)
                .addComponent(radBtnPosNeg)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radBtnOutraClassificacao)
                    .addComponent(tfOutraClassificacaoEsq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBarra)
                    .addComponent(tfOutraClassificacaoDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAssunto)
                    .addComponent(tfAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConfirmaSelecao)
                .addContainerGap(104, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmaSelecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmaSelecaoActionPerformed

        //Verifica se alguma opção está selecionada
        if(!radBtnNeutroOp.isSelected() && !radBtnOutraClassificacao.isSelected() && !radBtnPosNeg.isSelected()){

            JOptionPane.showMessageDialog(null, "Por favor, selecione alguma opção.", "Erro na operação!", JOptionPane.INFORMATION_MESSAGE);

        } else if (tfAssunto.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Por favor, preencha o campo assunto.", "Erro na operação!", JOptionPane.INFORMATION_MESSAGE);

        //Trata cada opção separadamente
        } else{

            if(radBtnNeutroOp.isSelected()){

                classificacaoEscolhida = radBtnNeutroOp.getText();

                btnConfirmaSelecao.setEnabled(false);
                TelaPrincipal.btnProximo.setEnabled(true);

                radBtnNeutroOp.setEnabled(false);
                radBtnOutraClassificacao.setEnabled(false);
                radBtnPosNeg.setEnabled(false);

                labelAssunto.setEnabled(false);
                tfAssunto.setEnabled(false);

            } else if (radBtnPosNeg.isSelected()){

                classificacaoEscolhida = radBtnPosNeg.getText();

                btnConfirmaSelecao.setEnabled(false);
                TelaPrincipal.btnProximo.setEnabled(true);

                radBtnNeutroOp.setEnabled(false);
                radBtnOutraClassificacao.setEnabled(false);
                radBtnPosNeg.setEnabled(false);

                labelAssunto.setEnabled(false);
                tfAssunto.setEnabled(false);

            } else if (radBtnOutraClassificacao.isSelected()){

                //Verifica se foi especificada qual classificacao se dejesa no casa de "outra"
                if(tfOutraClassificacaoEsq.getText().isEmpty() || tfOutraClassificacaoDir.getText().isEmpty()){
                    
                    JOptionPane.showMessageDialog(null, "Por favor, preencha o campo outro com algum tipo de classificação.","Erro na operação", JOptionPane.INFORMATION_MESSAGE);
                    
                } else {
                    
                    classificacaoEscolhida = tfOutraClassificacaoEsq.getText() + "/" + tfOutraClassificacaoDir.getText();
                    
                    btnConfirmaSelecao.setEnabled(false);
                    TelaPrincipal.btnProximo.setEnabled(true);

                    radBtnNeutroOp.setEnabled(false);
                    radBtnOutraClassificacao.setEnabled(false);
                    radBtnPosNeg.setEnabled(false);

                    labelAssunto.setEnabled(false);
                    tfAssunto.setEnabled(false);

                    tfOutraClassificacaoDir.setEnabled(false);
                    tfOutraClassificacaoEsq.setEnabled(false);
                    
                }


            }

            assunto = tfAssunto.getText();

        }

    }//GEN-LAST:event_btnConfirmaSelecaoActionPerformed

    private void radBtnOutraClassificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnOutraClassificacaoActionPerformed

        tfOutraClassificacaoEsq.setEnabled(true);
        tfOutraClassificacaoDir.setEnabled(true);

    }//GEN-LAST:event_radBtnOutraClassificacaoActionPerformed

    private void radBtnPosNegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnPosNegActionPerformed

        tfOutraClassificacaoEsq.setEnabled(false);
        tfOutraClassificacaoDir.setEnabled(false);

    }//GEN-LAST:event_radBtnPosNegActionPerformed

    private void radBtnNeutroOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnNeutroOpActionPerformed

        tfOutraClassificacaoEsq.setEnabled(false);
        tfOutraClassificacaoDir.setEnabled(false);

    }//GEN-LAST:event_radBtnNeutroOpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmaSelecao;
    private javax.swing.ButtonGroup btnGrupo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelAssunto;
    private javax.swing.JLabel labelBarra;
    private javax.swing.JRadioButton radBtnNeutroOp;
    private javax.swing.JRadioButton radBtnOutraClassificacao;
    private javax.swing.JRadioButton radBtnPosNeg;
    private javax.swing.JLabel textoConverterJson;
    private javax.swing.JTextField tfAssunto;
    private javax.swing.JTextField tfOutraClassificacaoDir;
    private javax.swing.JTextField tfOutraClassificacaoEsq;
    // End of variables declaration//GEN-END:variables

}
