/*Classe: TelaRemoveMsgIndesejadas
  Pacote: protototipominop.view
  Funcionalidade: Essa classe representa a tela na qual serão removidas mensagens
  indesejadas. Deve-se especificar os trechos que as mensagens não devem conter.
  Autor: Leandro Matioli Santos
*/

package protototipominop.view;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author Leandro
 */
public class TelaRemoveMsgIndesejadas extends javax.swing.JPanel {

    String arquivo;

    /** Creates new form TelaRemoveMsgIndesejadas */
    public TelaRemoveMsgIndesejadas() {
        initComponents();

        barraProgRemocao.setVisible(false);

        JFileChooser fileChooser = new JFileChooser();

        fileChooser.showOpenDialog(this);

        arquivo = fileChooser.getSelectedFile().getAbsolutePath();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTituloTela = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        tfTrechosRemover = new javax.swing.JTextField();
        labelSepareVirgulas = new javax.swing.JLabel();
        btnIniciarRemocao = new javax.swing.JButton();
        barraProgRemocao = new javax.swing.JProgressBar();

        setPreferredSize(new java.awt.Dimension(733, 428));

        labelTituloTela.setFont(new java.awt.Font("Tahoma", 0, 18));
        labelTituloTela.setText("Defina os trechos de texto que as mensagens não devem conter:");

        labelSepareVirgulas.setText("Obs: Separe cada trecho por vírgulas");

        btnIniciarRemocao.setText("Iniciar remoção");
        btnIniciarRemocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarRemocaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(labelTituloTela)
                            .addGap(102, 102, 102))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tfTrechosRemover, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelSepareVirgulas)
                        .addGap(272, 272, 272))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(294, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnIniciarRemocao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(barraProgRemocao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(293, 293, 293))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloTela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSepareVirgulas)
                .addGap(69, 69, 69)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfTrechosRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIniciarRemocao)
                .addGap(18, 18, 18)
                .addComponent(barraProgRemocao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarRemocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarRemocaoActionPerformed

        barraProgRemocao.setVisible(true);
        barraProgRemocao.setMaximum(TelaPrincipal.baseDeTextoController.contaLinhas(arquivo));
        barraProgRemocao.setStringPainted(true);

        //Cria um SwingWorker para não travar a tela e preencher a barra de progresso
        new SwingWorker<Object, Object>() {

            @Override
            protected Object doInBackground() throws Exception {

                //Gera um vetor contendo os trecho que as mensagens não devem conter
                String[] listaTrechos = tfTrechosRemover.getText().split(",");

                TelaPrincipal.baseDeTextoController.removeMensagensDesejadas(arquivo, listaTrechos);

                JOptionPane.showMessageDialog(null, "Mensagens removidas com sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

                return null;

            }

        }.execute();

        tfTrechosRemover.setEnabled(false);
        btnIniciarRemocao.setEnabled(false);

    }//GEN-LAST:event_btnIniciarRemocaoActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JProgressBar barraProgRemocao;
    private javax.swing.JButton btnIniciarRemocao;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelSepareVirgulas;
    public static javax.swing.JLabel labelTituloTela;
    private javax.swing.JTextField tfTrechosRemover;
    // End of variables declaration//GEN-END:variables

}
