/*Classe: TelaQuantidadeTextos
  Pacote: protototipominop.view
  Funcionalidade: Essa classe representa a tela na qual deve-se especificar as
  quantidades de mensagens desejadas para treino e teste.
  Autor: Leandro Matioli Santos
*/

package protototipominop.view;

import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author Leandro
 */
public class TelaQuantidadeTextos extends javax.swing.JPanel {

    public static int qtdSolicitadaTreino;
    public static int qtdSolicitadaTeste;
    public static int qtdTotalTextos;

    /** Creates new form NewJPanel */
    public TelaQuantidadeTextos() {
        initComponents();

        qtdTotalTextos = TelaPrincipal.baseDeTextoController.baseDeTextoModel.getQtdTextos();

        //Mostra a quantidade inicial de documentos contida no arquivo
        labelQtdTextoTotal.setText(Integer.toString(TelaPrincipal.baseDeTextoController.baseDeTextoModel.getQtdTextos()) + " documento(s)");
        
        //Esconde todas as labels e botoes que nao devem ser mostrados no inicio
        labelRestaramTreino.setVisible(false);
        labelQtdRestaramTreino.setVisible(false);
        btnConfirmaTreino.setVisible(false);

        labelInfoQtdTeste.setEnabled(false);
        tfQtdTeste.setEnabled(false);
        btnOkTeste.setEnabled(false);
        labelRestaramTeste.setVisible(false);
        labelQtdRestaramTeste.setVisible(false);
        btnConfirmaTeste.setVisible(false);

        labelGerarArquivos.setEnabled(false);
        btnGerarArquivos.setEnabled(false);
        btnRedefinirQtd.setEnabled(false);

        barraProgArquivosTreinoTeste.setVisible(false);
        //Fim trecho



    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSelecioneTitulo = new javax.swing.JLabel();
        labelInformaQtdTexto = new javax.swing.JLabel();
        labelQtdTextoTotal = new javax.swing.JLabel();
        labelInfoQtdTreinamento = new javax.swing.JLabel();
        tfQtdTreino = new javax.swing.JTextField();
        tfQtdTeste = new javax.swing.JTextField();
        labelInfoQtdTeste = new javax.swing.JLabel();
        labelRestaramTreino = new javax.swing.JLabel();
        labelQtdRestaramTreino = new javax.swing.JLabel();
        btnOkTreino = new javax.swing.JButton();
        btnOkTeste = new javax.swing.JButton();
        labelRestaramTeste = new javax.swing.JLabel();
        labelQtdRestaramTeste = new javax.swing.JLabel();
        labelGerarArquivos = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnGerarArquivos = new javax.swing.JButton();
        btnConfirmaTreino = new javax.swing.JButton();
        btnConfirmaTeste = new javax.swing.JButton();
        btnRedefinirQtd = new javax.swing.JButton();
        barraProgArquivosTreinoTeste = new javax.swing.JProgressBar();

        setPreferredSize(new java.awt.Dimension(733, 428));

        labelSelecioneTitulo.setFont(new java.awt.Font("Tahoma", 0, 18));
        labelSelecioneTitulo.setText("Selecione a quantidade de documentos para realizar o treinamento e teste:");

        labelInformaQtdTexto.setText("Sua base de texto selecionada contém:");

        labelInfoQtdTreinamento.setText("Quantidade desejada para treinamento: ");

        tfQtdTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQtdTreinoActionPerformed(evt);
            }
        });

        tfQtdTeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQtdTesteActionPerformed(evt);
            }
        });

        labelInfoQtdTeste.setText("Quantidade desejada para teste: ");

        labelRestaramTreino.setText("Restaram:");

        btnOkTreino.setText("OK");
        btnOkTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkTreinoActionPerformed(evt);
            }
        });

        btnOkTeste.setText("OK");
        btnOkTeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkTesteActionPerformed(evt);
            }
        });

        labelRestaramTeste.setText("Restaram:");

        labelGerarArquivos.setText("Gerar arquivos com as quantidades especificadas?");

        btnGerarArquivos.setText("Gerar arquivos");
        btnGerarArquivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarArquivosActionPerformed(evt);
            }
        });

        btnConfirmaTreino.setText("Confirma");
        btnConfirmaTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmaTreinoActionPerformed(evt);
            }
        });

        btnConfirmaTeste.setText("Confirma");
        btnConfirmaTeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmaTesteActionPerformed(evt);
            }
        });

        btnRedefinirQtd.setText("Redefinir quantidades");
        btnRedefinirQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedefinirQtdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(labelSelecioneTitulo)
                            .addGap(64, 64, 64))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(labelInformaQtdTexto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(labelQtdTextoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(101, 101, 101))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelInfoQtdTreinamento)
                                .addComponent(labelInfoQtdTeste))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tfQtdTreino, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(btnOkTreino)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                    .addComponent(labelRestaramTreino)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(labelQtdRestaramTreino, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tfQtdTeste, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnOkTeste)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                    .addComponent(labelRestaramTeste)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(labelQtdRestaramTeste, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnConfirmaTeste)
                                .addComponent(btnConfirmaTreino))
                            .addContainerGap(107, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addComponent(labelGerarArquivos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnRedefinirQtd)
                                    .addGap(36, 36, 36)
                                    .addComponent(btnGerarArquivos, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(196, 196, 196)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(barraProgArquivosTreinoTeste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(279, 279, 279))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSelecioneTitulo)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelInformaQtdTexto)
                    .addComponent(labelQtdTextoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelInfoQtdTreinamento)
                        .addComponent(tfQtdTreino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnOkTreino)
                        .addComponent(labelRestaramTreino))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnConfirmaTreino)
                        .addComponent(labelQtdRestaramTreino, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfQtdTeste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelInfoQtdTeste)
                        .addComponent(btnOkTeste))
                    .addComponent(btnConfirmaTeste)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(labelQtdRestaramTeste, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelRestaramTeste)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(labelGerarArquivos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRedefinirQtd)
                    .addComponent(btnGerarArquivos))
                .addGap(31, 31, 31)
                .addComponent(barraProgArquivosTreinoTeste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkTreinoActionPerformed

        //Inicializa-se as variaveis
        int qtdRestanteTreino = 0;
        boolean digitouInteiro = false;

        //Verifica se o que foi digitado eh um numero inteiro
        try{

            qtdSolicitadaTreino = Integer.valueOf(tfQtdTreino.getText());
            digitouInteiro = true;

        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Por favor, digite um valor inteiro.", "Erro na operação!", JOptionPane.WARNING_MESSAGE);
        }

        //So realiza a exibicao na tela se o valor digitado for um numero inteiro
        if(digitouInteiro){

            if(qtdSolicitadaTreino < 0){

                JOptionPane.showMessageDialog(null, "Quantidade solicitada menor que 0. Valor inválido.", "Erro na operação!", JOptionPane.WARNING_MESSAGE);

            } else {

                //Verifica se quantidade solicitada nao excede a quantidade disponivel
                if (qtdTotalTextos - qtdSolicitadaTreino >=0 ){

                    labelRestaramTreino.setVisible(true);
                    labelRestaramTreino.setEnabled(true);

                    //Calcula quantidade restantes apos determinacao do numero
                    qtdRestanteTreino = qtdTotalTextos - qtdSolicitadaTreino;

                    //Mostra na tela a quantidade restante
                    labelQtdRestaramTreino.setText(Integer.toString(qtdRestanteTreino) + " documento(s)");

                    labelQtdRestaramTreino.setVisible(true);
                    labelQtdRestaramTreino.setEnabled(true);

                    btnConfirmaTreino.setVisible(true);
                    btnConfirmaTreino.setEnabled(true);

                } else {
                    JOptionPane.showMessageDialog(null, "Quantidade solicitada maior que a disponivel.", "Erro na operação!", JOptionPane.WARNING_MESSAGE);
                }

            }

        }

    }//GEN-LAST:event_btnOkTreinoActionPerformed

    private void btnOkTesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkTesteActionPerformed

        //Inicializa as variaveis
        int qtdRestanteTeste = 0;
        boolean digitouInteiro = false;

        //Verifica se o valor digitado eh um valor inteiro
        try{

            qtdSolicitadaTeste = Integer.valueOf(tfQtdTeste.getText());
            digitouInteiro = true;

        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Por favor, digite um valor inteiro.", "Erro na operação!", JOptionPane.WARNING_MESSAGE);
        }

        //So realiza a exibicao na tela se o valor digitado for um numero inteiro
        if(digitouInteiro){

            if(qtdSolicitadaTeste < 0){

                JOptionPane.showMessageDialog(null, "Quantidade solicitada menor que 0. Valor inválido.", "Erro na operação!", JOptionPane.WARNING_MESSAGE);

            } else {

                //Calcula a quantidade restante para teste
                qtdRestanteTeste = (qtdTotalTextos - qtdSolicitadaTreino) - qtdSolicitadaTeste;

                if(qtdRestanteTeste >= 0){

                    labelRestaramTeste.setVisible(true);
                    labelRestaramTeste.setEnabled(true);

                    //Mostra a quantidade na tela
                    labelQtdRestaramTeste.setText(Integer.valueOf(qtdRestanteTeste) + " documento(s)");
                    labelQtdRestaramTeste.setVisible(true);
                    labelQtdRestaramTeste.setEnabled(true);

                    btnConfirmaTeste.setVisible(true);
                    btnConfirmaTeste.setEnabled(true);

                } else{
                    JOptionPane.showMessageDialog(null, "Quantidade solicitada maior que a disponivel.", "Erro na operação!", JOptionPane.WARNING_MESSAGE);
                }

            }


            
           
        }

    }//GEN-LAST:event_btnOkTesteActionPerformed

    private void btnConfirmaTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmaTreinoActionPerformed

            //Impossibilita edicao dos valores de treino
            labelInfoQtdTreinamento.setEnabled(false);
            tfQtdTreino.setEnabled(false);
            btnOkTreino.setEnabled(false);
            labelRestaramTreino.setEnabled(false);
            labelQtdRestaramTreino.setEnabled(false);
            btnConfirmaTreino.setEnabled(false);

            if(qtdSolicitadaTreino != 0){

                //Possibilita edicao dos valores de teste
                labelInfoQtdTeste.setEnabled(true);
                tfQtdTeste.setEnabled(true);
                btnOkTeste.setEnabled(true);

                tfQtdTeste.requestFocus();

            } else {

                tfQtdTeste.setText("0");
                btnOkTeste.setEnabled(true);
                btnOkTeste.doClick();
                btnConfirmaTeste.doClick();
                
            }

            

    }//GEN-LAST:event_btnConfirmaTreinoActionPerformed

    private void btnConfirmaTesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmaTesteActionPerformed

        //Impossibilita edicao dos valores de teste
        labelInfoQtdTeste.setEnabled(false);
        tfQtdTeste.setEnabled(false);
        btnOkTeste.setEnabled(false);
        labelRestaramTeste.setEnabled(false);
        labelQtdRestaramTeste.setEnabled(false);
        btnConfirmaTeste.setEnabled(false);

        //Possibilita a geracao dos arquivos ou redefinicao dos valores
        labelGerarArquivos.setEnabled(true);
        btnGerarArquivos.setEnabled(true);
        btnRedefinirQtd.setEnabled(true);
    }//GEN-LAST:event_btnConfirmaTesteActionPerformed

    private void btnRedefinirQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedefinirQtdActionPerformed

        //Apaga tudo que foi exibido, deixando a tela como ela era inicialmente
        tfQtdTeste.setText("");
        tfQtdTreino.setText("");
        labelInfoQtdTreinamento.setEnabled(true);
        tfQtdTreino.setEnabled(true);
        btnOkTreino.setEnabled(true);

        labelRestaramTreino.setVisible(false);
        labelQtdRestaramTreino.setVisible(false);
        btnConfirmaTreino.setVisible(false);

        labelInfoQtdTeste.setEnabled(false);
        tfQtdTeste.setEnabled(false);
        btnOkTeste.setEnabled(false);
        labelRestaramTeste.setVisible(false);
        labelQtdRestaramTeste.setVisible(false);
        btnConfirmaTeste.setVisible(false);

        labelGerarArquivos.setEnabled(false);
        btnGerarArquivos.setEnabled(false);
        btnRedefinirQtd.setEnabled(false);
        //Fim Trecho

        tfQtdTreino.requestFocus();

}//GEN-LAST:event_btnRedefinirQtdActionPerformed

    private void btnGerarArquivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarArquivosActionPerformed

        barraProgArquivosTreinoTeste.setMaximum(TelaPrincipal.baseDeTextoController.baseDeTextoModel.getQtdTextos());
        barraProgArquivosTreinoTeste.setStringPainted(true);
        barraProgArquivosTreinoTeste.setVisible(true);

        //Impossibilita redefinir quantidade, ja que optou-se por gerar os arquivos
        btnRedefinirQtd.setEnabled(false);
        
        btnGerarArquivos.setEnabled(false);
        labelGerarArquivos.setEnabled(false);

        //Cria um SwingWorker para não travar a tela e preencher a barra de progresso
        new SwingWorker() {

            @Override
            protected Object doInBackground() throws Exception {

                TelaPrincipal.baseDeTextoController.selecionaAmostraParaTreinoETeste(qtdSolicitadaTreino, qtdSolicitadaTeste, TelaPrincipal.baseDeTextoController.baseDeTextoModel);

                TelaPrincipal.btnProximo.setEnabled(true);

                if(qtdSolicitadaTreino == 0 && qtdSolicitadaTeste == 0){
                    TelaPrincipal.telaAtual = 11;
                }

                return null;

            }

        }.execute();

        
    }//GEN-LAST:event_btnGerarArquivosActionPerformed

    private void tfQtdTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQtdTreinoActionPerformed
        btnOkTreinoActionPerformed(evt);
    }//GEN-LAST:event_tfQtdTreinoActionPerformed

    private void tfQtdTesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQtdTesteActionPerformed
        btnOkTesteActionPerformed(evt);
    }//GEN-LAST:event_tfQtdTesteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JProgressBar barraProgArquivosTreinoTeste;
    private javax.swing.JButton btnConfirmaTeste;
    private javax.swing.JButton btnConfirmaTreino;
    private javax.swing.JButton btnGerarArquivos;
    private javax.swing.JButton btnOkTeste;
    private javax.swing.JButton btnOkTreino;
    private javax.swing.JButton btnRedefinirQtd;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelGerarArquivos;
    private javax.swing.JLabel labelInfoQtdTeste;
    private javax.swing.JLabel labelInfoQtdTreinamento;
    private javax.swing.JLabel labelInformaQtdTexto;
    private javax.swing.JLabel labelQtdRestaramTeste;
    private javax.swing.JLabel labelQtdRestaramTreino;
    private javax.swing.JLabel labelQtdTextoTotal;
    private javax.swing.JLabel labelRestaramTeste;
    private javax.swing.JLabel labelRestaramTreino;
    private javax.swing.JLabel labelSelecioneTitulo;
    private javax.swing.JTextField tfQtdTeste;
    private javax.swing.JTextField tfQtdTreino;
    // End of variables declaration//GEN-END:variables

}
