/*Classe: TelaIdioma
  Pacote: protototipominop.view
  Funcionalidade: Essa classe representa a tela na qual define-se em qual idioma
  deve-se filtrar a coleção.
  Autor: Leandro Matioli Santos
*/

package protototipominop.view;

import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author Leandro
 */
public class TelaIdioma extends javax.swing.JPanel {

    /** Creates new form TelaIdioma */
    public TelaIdioma() {
        initComponents();

        //Adiciona os botoes no grupo para permitir selecionar apenas um por vez
        btnGrGrupoLingua.add(radBtnIngles);
        btnGrGrupoLingua.add(radBtnPortugues);
        btnGrGrupoLingua.add(radBtnEspanhol);

        //Coloca a barra de progresso invísivel, ate realmente iniciar o processamento
        barraProgIdioma.setVisible(false);



    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrGrupoLingua = new javax.swing.ButtonGroup();
        textoSelecioneLingua = new javax.swing.JLabel();
        radBtnIngles = new javax.swing.JRadioButton();
        radBtnPortugues = new javax.swing.JRadioButton();
        radBtnEspanhol = new javax.swing.JRadioButton();
        btnFiltraTexto = new javax.swing.JButton();
        btnPulaEtapa = new javax.swing.JButton();
        barraProgIdioma = new javax.swing.JProgressBar();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(733, 428));

        textoSelecioneLingua.setFont(new java.awt.Font("Tahoma", 0, 18));
        textoSelecioneLingua.setText("Selecione a língua desejada para filtrar a sua coleção de textos:");

        radBtnIngles.setText("Inglês");

        radBtnPortugues.setText("Português");

        radBtnEspanhol.setText("Espanhol");

        btnFiltraTexto.setText("Filtrar Língua");
        btnFiltraTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltraTextoActionPerformed(evt);
            }
        });

        btnPulaEtapa.setText("Pular Etapa");
        btnPulaEtapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPulaEtapaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(textoSelecioneLingua)
                .addGap(101, 101, 101))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radBtnPortugues)
                            .addComponent(radBtnIngles)
                            .addComponent(radBtnEspanhol))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFiltraTexto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(btnPulaEtapa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(barraProgIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(312, 312, 312))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoSelecioneLingua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radBtnIngles)
                .addGap(18, 18, 18)
                .addComponent(radBtnPortugues)
                .addGap(18, 18, 18)
                .addComponent(radBtnEspanhol)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFiltraTexto)
                .addGap(18, 18, 18)
                .addComponent(btnPulaEtapa)
                .addGap(18, 18, 18)
                .addComponent(barraProgIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltraTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltraTextoActionPerformed

        barraProgIdioma.setMaximum(TelaPrincipal.baseDeTextoController.baseDeTextoModel.getQtdTextos());
        barraProgIdioma.setStringPainted(true);

        //Se o arquivo com a identificação das linguas não existir, avisa ao usuário que ele deve realizar a identificação antes.
        if(!TelaPrincipal.baseDeTextoController.verificaExistenciaArquivo(TelaPrincipal.baseDeTextoController.baseDeTextoModel.getCaminhoAbsoluto() + "-IDLINGUAS")){

            JOptionPane.showMessageDialog(null, "Arquivo com a identificação das línguas não encontrado. Por favor, realize a identificação através da opção Identificar idiomas de um arquivo.", "Problemas na operação.", JOptionPane.INFORMATION_MESSAGE);

        //Caso o arquivo exista, realiza-se a identificação de acordo com a lingua especificada
        } else {

            //Nao permite pular etapa, ja que realizou-se a filtragem
            btnPulaEtapa.setEnabled(false);

            if(radBtnIngles.isSelected()){

                //Cria um SwingWorker para não travar a tela e preencher a barra de progresso
                new SwingWorker<Object, Object>() {

                    @Override
                    protected Object doInBackground() throws Exception {

                        btnFiltraTexto.setEnabled(false);

                        radBtnEspanhol.setEnabled(false);
                        radBtnIngles.setEnabled(false);
                        radBtnPortugues.setEnabled(false);

                        TelaPrincipal.baseDeTextoController.filtraLingua(TelaPrincipal.baseDeTextoController.baseDeTextoModel.getCaminhoAbsoluto(),
                                                                         TelaPrincipal.baseDeTextoController.baseDeTextoModel.getCaminhoAbsoluto() + "-IDLINGUAS",
                                                                         "Inglês");                
                        
                        TelaPrincipal.btnProximo.setEnabled(true);

                        try {

                            TelaPrincipal.baseDeTextoController.baseDeTextoModel = TelaPrincipal.baseDeTextoController.inserirBaseDeTextoUnicoArquivo(TelaPrincipal.baseDeTextoController.baseDeTextoModel.getCaminhoAbsoluto() + "-INGLÊS");

                        } catch (IOException ex) {
                            System.out.println(ex);
                        }

                        return null;
                    }

                }.execute();

                barraProgIdioma.setVisible(true);

            } else if (radBtnPortugues.isSelected()){

                //Cria um SwingWorker para não travar a tela e preencher a barra de progresso
                new SwingWorker<Object, Object>() {
                
                    @Override
                    protected Object doInBackground() throws Exception {
                        
                        btnFiltraTexto.setEnabled(false);

                        radBtnEspanhol.setEnabled(false);
                        radBtnIngles.setEnabled(false);
                        radBtnPortugues.setEnabled(false);
                        
                        TelaPrincipal.baseDeTextoController.filtraLingua(TelaPrincipal.baseDeTextoController.baseDeTextoModel.getCaminhoAbsoluto(),
                                                                         TelaPrincipal.baseDeTextoController.baseDeTextoModel.getCaminhoAbsoluto() + "-IDLINGUAS",
                                                                         "Português");

                        try {

                            TelaPrincipal.baseDeTextoController.baseDeTextoModel = TelaPrincipal.baseDeTextoController.inserirBaseDeTextoUnicoArquivo(TelaPrincipal.baseDeTextoController.baseDeTextoModel.getCaminhoAbsoluto() + "-PORTUGUÊS");

                        } catch (IOException ex) {
                            System.out.println(ex);
                        }
                        
                        TelaPrincipal.btnProximo.setEnabled(true);

                        return null;
                        
                    }

                }.execute();

                barraProgIdioma.setVisible(true);
                

            } else if(radBtnEspanhol.isSelected()){

                //Cria um SwingWorker para não travar a tela e preencher a barra de progresso
                new SwingWorker<Object, Object>() {

                    @Override
                    protected Object doInBackground() throws Exception {

                        btnFiltraTexto.setEnabled(false);

                        radBtnEspanhol.setEnabled(false);
                        radBtnIngles.setEnabled(false);
                        radBtnPortugues.setEnabled(false);

                        TelaPrincipal.baseDeTextoController.filtraLingua(TelaPrincipal.baseDeTextoController.baseDeTextoModel.getCaminhoAbsoluto(),
                                                                         TelaPrincipal.baseDeTextoController.baseDeTextoModel.getCaminhoAbsoluto() + "-IDLINGUAS",
                                                                         "Espanhol");

                        try {

                            TelaPrincipal.baseDeTextoController.baseDeTextoModel = TelaPrincipal.baseDeTextoController.inserirBaseDeTextoUnicoArquivo(TelaPrincipal.baseDeTextoController.baseDeTextoModel.getCaminhoAbsoluto() + "-ESPANHOL");

                        } catch (IOException ex) {
                            System.out.println(ex);
                        }
                        
                        TelaPrincipal.btnProximo.setEnabled(true);
                        
                        return null;

                    }
                }.execute();
               
                barraProgIdioma.setVisible(true);

            //Caso nenhuma opção tenha sido selecionada, mostra msg avisando do problema
            } else {

                btnPulaEtapa.setEnabled(true);
                JOptionPane.showMessageDialog(null,"Por favor, selecione um idioma.","Erro na operação",JOptionPane.WARNING_MESSAGE);

            }
        }

        
        
        



}//GEN-LAST:event_btnFiltraTextoActionPerformed

    private void btnPulaEtapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPulaEtapaActionPerformed

        //Indisponibiliza as opções para click, já que optou-se por pular a etapa
        radBtnIngles.setEnabled(false);
        radBtnPortugues.setEnabled(false);
        radBtnEspanhol.setEnabled(false);

        btnFiltraTexto.setEnabled(false);
        btnPulaEtapa.setEnabled(false);

        TelaPrincipal.btnProximo.setEnabled(true);

}//GEN-LAST:event_btnPulaEtapaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JProgressBar barraProgIdioma;
    private javax.swing.JButton btnFiltraTexto;
    private javax.swing.ButtonGroup btnGrGrupoLingua;
    private javax.swing.JButton btnPulaEtapa;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton radBtnEspanhol;
    private javax.swing.JRadioButton radBtnIngles;
    private javax.swing.JRadioButton radBtnPortugues;
    private javax.swing.JLabel textoSelecioneLingua;
    // End of variables declaration//GEN-END:variables

}
