/*Classe: TelaDecideValidadeTreino
  Pacote: protototipominop.view
  Funcionalidade: Essa classe representa a tela na qual deve-se decidir se o treinamento
  realizado foi razoável para a classificação de mensagens desconhecidas.
  Autor: Leandro Matioli Santos
*/

package protototipominop.view;

/**
 *
 * @author Leandro
 */
public class TelaDecideValidadeTreino extends javax.swing.JPanel {

    /** Creates new form TelaDecideValidadeTreino */
    public TelaDecideValidadeTreino() {
        initComponents();

        //Recupera o caminho dos arquivos que serão utilizados
        String arquivoParaClassificar = TelaPrincipal.baseDeTextoController.baseDeTextoModel.getCaminhoAbsoluto()+"-TESTE-PREPROCESSADO";
        String arquivoModelo = "./svm/modelosSvm/" + TelaPrincipal.baseDeTextoController.retornaNomeArquivo(TelaPrincipal.baseDeTextoController.baseDeTextoModel.getCaminhoAbsoluto()) + "-MODELOSVM";
        String saidaSVM = TelaPrincipal.baseDeTextoController.retornaNomeArquivo(TelaPrincipal.baseDeTextoController.baseDeTextoModel.getCaminhoAbsoluto()) + "-SAIDATESTE";

        textAreaSaidaTeste.setEditable(false);
        btnConfirmarClassificacao.setEnabled(false);
        btnVoltarTreinamento.setEnabled(false);

        TelaPrincipal.baseDeTextoController.realizaClassificacao(arquivoParaClassificar, arquivoModelo, saidaSVM);

        btnConfirmarClassificacao.setEnabled(true);
        btnVoltarTreinamento.setEnabled(true);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoDecideValidadeTreino = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaSaidaTeste = new javax.swing.JTextArea();
        btnConfirmarClassificacao = new javax.swing.JButton();
        btnVoltarTreinamento = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(733, 428));

        textoDecideValidadeTreino.setFont(new java.awt.Font("Tahoma", 0, 18));
        textoDecideValidadeTreino.setText("Selecione a opção desejada de acordo com o resultado obtido no treino:");

        textAreaSaidaTeste.setColumns(20);
        textAreaSaidaTeste.setRows(5);
        jScrollPane1.setViewportView(textAreaSaidaTeste);

        btnConfirmarClassificacao.setText("Confirmar Treinamento Realizado");
        btnConfirmarClassificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarClassificacaoActionPerformed(evt);
            }
        });

        btnVoltarTreinamento.setText("Realizar Treinamento Novamente");
        btnVoltarTreinamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarTreinamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(textoDecideValidadeTreino))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(btnVoltarTreinamento, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addGap(102, 102, 102)
                .addComponent(btnConfirmarClassificacao, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoDecideValidadeTreino)
                .addGap(55, 55, 55)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltarTreinamento)
                    .addComponent(btnConfirmarClassificacao))
                .addGap(107, 107, 107))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarClassificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarClassificacaoActionPerformed

        btnConfirmarClassificacao.setEnabled(false);
        btnVoltarTreinamento.setEnabled(false);
        textAreaSaidaTeste.setEditable(false);

        TelaPrincipal.btnProximo.setEnabled(true);

}//GEN-LAST:event_btnConfirmarClassificacaoActionPerformed

    private void btnVoltarTreinamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarTreinamentoActionPerformed

        //Seta o valor de tela atual como se fosse a tela anterior à tela de decidir a qtd de docs utilizada para cada etapa
        TelaPrincipal.telaAtual = 1;

        TelaPrincipal.btnProximo.setEnabled(true);
        TelaPrincipal.btnProximo.doClick();

    }//GEN-LAST:event_btnVoltarTreinamentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarClassificacao;
    private javax.swing.JButton btnVoltarTreinamento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public static javax.swing.JTextArea textAreaSaidaTeste;
    private javax.swing.JLabel textoDecideValidadeTreino;
    // End of variables declaration//GEN-END:variables

}
