/*Classe: TelaUtilizaModeloExistente
  Pacote: protototipominop.view
  Funcionalidade: Essa classe representa a tela na qual deve-se definir os arquivos
  (o modelo já treinado e o arquivo a ser classificado) para realizar uma classificação
  utilizando um modelo previamente gerado.
  Autor: Leandro Matioli Santos
*/

package protototipominop.view;

import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Leandro
 */
public class TelaUtilizaModeloExistente extends javax.swing.JPanel {

    public static String arquivoModelo;
    public static String arquivoClassifica;
    public static boolean jaPreProcessado = false;


    /** Creates new form TelaUtilizaModeloExistente */
    public TelaUtilizaModeloExistente() {
        initComponents();

        tfCaminhoArqClassifica.setEditable(false);
        tfCaminhoArqModelo.setEditable(false);

        labelEstaPreProcessado.setVisible(false);
        btnSimPreProcessado.setVisible(false);
        btnNaoPreProcessado.setVisible(false);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texoSelecionarArquivos = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        labelArqModelo = new javax.swing.JLabel();
        labelArqClassifica = new javax.swing.JLabel();
        btnSelecionarModelo = new javax.swing.JButton();
        btnSelecionarClassifica = new javax.swing.JButton();
        tfCaminhoArqModelo = new javax.swing.JTextField();
        tfCaminhoArqClassifica = new javax.swing.JTextField();
        btnConfirmaArquivos = new javax.swing.JButton();
        labelEstaPreProcessado = new javax.swing.JLabel();
        btnSimPreProcessado = new javax.swing.JButton();
        btnNaoPreProcessado = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(733, 428));

        texoSelecionarArquivos.setFont(new java.awt.Font("Tahoma", 0, 18));
        texoSelecionarArquivos.setText("Selecione os arquivos para a classificação:");

        labelArqModelo.setText("Arquivo do modelo já treinado: ");

        labelArqClassifica.setText("Arquivo a ser classificado: ");

        btnSelecionarModelo.setText("Selecionar");
        btnSelecionarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarModeloActionPerformed(evt);
            }
        });

        btnSelecionarClassifica.setText("Selecionar");
        btnSelecionarClassifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarClassificaActionPerformed(evt);
            }
        });

        btnConfirmaArquivos.setText("Confirma Arquivos");
        btnConfirmaArquivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmaArquivosActionPerformed(evt);
            }
        });

        labelEstaPreProcessado.setText("O arquivo a ser classificadao já está pré-processado?");

        btnSimPreProcessado.setText("Sim");
        btnSimPreProcessado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimPreProcessadoActionPerformed(evt);
            }
        });

        btnNaoPreProcessado.setText("Não");
        btnNaoPreProcessado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNaoPreProcessadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(texoSelecionarArquivos))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelArqModelo)
                            .addComponent(labelArqClassifica))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSelecionarModelo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCaminhoArqModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSelecionarClassifica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCaminhoArqClassifica, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(242, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEstaPreProcessado)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnNaoPreProcessado)
                        .addGap(18, 18, 18)
                        .addComponent(btnSimPreProcessado)))
                .addGap(235, 235, 235))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnConfirmaArquivos)
                        .addGap(294, 294, 294)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texoSelecionarArquivos)
                .addGap(67, 67, 67)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelArqModelo)
                    .addComponent(btnSelecionarModelo)
                    .addComponent(tfCaminhoArqModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelecionarClassifica)
                    .addComponent(labelArqClassifica)
                    .addComponent(tfCaminhoArqClassifica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnConfirmaArquivos)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(labelEstaPreProcessado)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimPreProcessado)
                    .addComponent(btnNaoPreProcessado))
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecionarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarModeloActionPerformed

        JFileChooser fileChooser = new JFileChooser();

        fileChooser.setCurrentDirectory(TelaPrincipal.diretorioModelos);

        fileChooser.showOpenDialog(this);

        tfCaminhoArqModelo.setText(fileChooser.getSelectedFile().getAbsolutePath());
        arquivoModelo = fileChooser.getSelectedFile().getAbsolutePath();


    }//GEN-LAST:event_btnSelecionarModeloActionPerformed

    private void btnSelecionarClassificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarClassificaActionPerformed

        JFileChooser fileChooser = new JFileChooser();

        fileChooser.showOpenDialog(this);

        tfCaminhoArqClassifica.setText(fileChooser.getSelectedFile().getAbsolutePath());
        arquivoClassifica = fileChooser.getSelectedFile().getAbsolutePath();

    }//GEN-LAST:event_btnSelecionarClassificaActionPerformed

    private void btnConfirmaArquivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmaArquivosActionPerformed

        //Verifica se algum arquivo nao foi especificado
        if(tfCaminhoArqClassifica.getText().isEmpty() || tfCaminhoArqModelo.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Por favor, selecione os dois arquivos necessários.", "Erro na operação!", JOptionPane.WARNING_MESSAGE);
            
        } else {
            
            labelEstaPreProcessado.setVisible(true);
            btnSimPreProcessado.setVisible(true);
            btnNaoPreProcessado.setVisible(true);

            btnSelecionarModelo.setEnabled(false);
            btnSelecionarClassifica.setEnabled(false);
            btnConfirmaArquivos.setEnabled(false);

            labelArqClassifica.setEnabled(false);
            labelArqModelo.setEnabled(false);

        }





}//GEN-LAST:event_btnConfirmaArquivosActionPerformed

    private void btnNaoPreProcessadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNaoPreProcessadoActionPerformed

        jaPreProcessado = false;
        TelaPrincipal.telaAtual = -1;

        TelaPrincipal.btnProximo.setVisible(true);
        TelaPrincipal.btnProximo.setEnabled(true);

        btnNaoPreProcessado.setEnabled(false);
        btnSimPreProcessado.setEnabled(false);

        try {

            System.out.println(arquivoClassifica);
            
            //Monta uma base de texto de acordo com o arquivo selecionado
            TelaPrincipal.baseDeTextoController.baseDeTextoModel = TelaPrincipal.baseDeTextoController.inserirBaseDeTextoUnicoArquivo(arquivoClassifica);

        } catch (IOException ex) {
            System.out.println(ex);
        }


    }//GEN-LAST:event_btnNaoPreProcessadoActionPerformed

    private void btnSimPreProcessadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimPreProcessadoActionPerformed

        jaPreProcessado = true;
        
        //Coloca o indice das telas apontando para uma tela anterior à da classificação final
        TelaPrincipal.telaAtual = 7;

        labelEstaPreProcessado.setEnabled(false);

        btnNaoPreProcessado.setEnabled(false);
        btnSimPreProcessado.setEnabled(false);

        try {

            //Monta uma base de texto de acordo com o arquivo selecionado
            TelaPrincipal.baseDeTextoController.baseDeTextoModel = TelaPrincipal.baseDeTextoController.inserirBaseDeTextoUnicoArquivo(arquivoClassifica);

        } catch (IOException ex) {
            System.out.println(ex);
        }

        TelaPrincipal.btnProximo.setVisible(true);
        TelaPrincipal.btnProximo.setEnabled(true);

    }//GEN-LAST:event_btnSimPreProcessadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmaArquivos;
    private javax.swing.JButton btnNaoPreProcessado;
    private javax.swing.JButton btnSelecionarClassifica;
    private javax.swing.JButton btnSelecionarModelo;
    private javax.swing.JButton btnSimPreProcessado;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelArqClassifica;
    private javax.swing.JLabel labelArqModelo;
    private javax.swing.JLabel labelEstaPreProcessado;
    private javax.swing.JLabel texoSelecionarArquivos;
    private javax.swing.JTextField tfCaminhoArqClassifica;
    private javax.swing.JTextField tfCaminhoArqModelo;
    // End of variables declaration//GEN-END:variables

}
